name: Create Releases
on:
    workflow_dispatch:
jobs:
    create-prerelease:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - uses: actions/checkout@v4
            - name: Download all artifacts
              uses: actions/download-artifact@v4
              with:
                  path: artifacts
            - name: Unzip and rename artifacts
              run: |
                  mkdir unzipped
                  ls -lRa artifacts
                  ls -lRa
                  for dir in artifacts/*-build; do
                      platform=$(basename "$dir" -build)
                      unzip -j "$dir" -d "unzipped/$platform"
                      for file in unzipped/$platform/*; do
                      if [[ -f "$file" ]]; then
                          extension="${file##*.}"
                          new_name="${platform}-SharpTree.${extension}"
                          mv "$file" "unzipped/$platform/$new_name"
                      fi
                      done
                  done
                  ls -lRa unzipped
            - name: Create prerelease
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  tag_name="v$(date +'%Y.%m.%d-%H%M')"
                  gh release create $tag_name \
                      --title "Prerelease $tag_name" \
                      --notes "Auto-generated prerelease for commit ${{ github.sha }}" \
                      --prerelease \
                      unzipped/*/*
